[tool.poetry]
name = "a-maze-ing"
version = "1.0.0"
description = "Maze generator for 42"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
mypy = "^1.20.2"
pytest = "^9.0.3"

# Esta línea es crucial para incluir tus módulos dentro de src/
[[tool.poetry.packages]]
include = "src"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"